/*
 * Entry: 005caa41
 * Name: `dynamic_initializer_for_'codes''
 * Namespace: Global
 * Signature: void `dynamic_initializer_for_'codes''(void)
 * Symbol source: IMPORTED
 * Export status: ok
 */

void __cdecl _dynamic_initializer_for__codes__(void)

{
  codes[0] = StrToID("avapc");
  codes[1] = StrToID("avartl");
  codes[2] = StrToID("avcnst");
  codes[3] = StrToID("avfigh");
  codes[4] = StrToID("avhaul");
  codes[5] = StrToID("avhraz");
  codes[6] = StrToID("avltnk");
  codes[7] = StrToID("avmine");
  codes[8] = StrToID("avmuf");
  codes[9] = StrToID("avrckt");
  codes[10] = StrToID("avrecy");
  codes[0xb] = StrToID("avsav");
  codes[0xc] = StrToID("avscav");
  codes[0xd] = StrToID("avslf");
  codes[0xe] = StrToID("avtank");
  codes[0xf] = StrToID("avturr");
  codes[0x10] = StrToID("avwalk");
  codes[0x11] = StrToID("abbarr");
  codes[0x12] = StrToID("abcafe");
  codes[0x13] = StrToID("abcomm");
  codes[0x14] = StrToID("abhang");
  codes[0x15] = StrToID("abhqcp");
  codes[0x16] = StrToID("ablpad");
  codes[0x17] = StrToID("ablpow");
  codes[0x18] = StrToID("abshld");
  codes[0x19] = StrToID("absilo");
  codes[0x1a] = StrToID("abspow");
  codes[0x1b] = StrToID("abstor");
  codes[0x1c] = StrToID("absupp");
  codes[0x1d] = StrToID("abtowe");
  codes[0x1e] = StrToID("abtowe2");
  codes[0x1f] = StrToID("abwpow");
  codes[0x20] = StrToID("avland");
  codes[0x21] = StrToID("aspilo");
  codes[0x22] = StrToID("assold");
  codes[0x23] = StrToID("asuser");
  codes[0x24] = StrToID("bbbar");
  codes[0x25] = StrToID("bbcom2");
  codes[0x26] = StrToID("bbcomm");
  codes[0x27] = StrToID("bbhqcp");
  codes[0x28] = StrToID("bvhpc");
  codes[0x29] = StrToID("bvartl");
  codes[0x2a] = StrToID("bvhaul");
  codes[0x2b] = StrToID("bvhraz");
  codes[0x2c] = StrToID("bvltnk");
  codes[0x2d] = StrToID("bvmine");
  codes[0x2e] = StrToID("bvmuf");
  codes[0x2f] = StrToID("bvraz");
  codes[0x30] = StrToID("bvrckt");
  codes[0x31] = StrToID("bvrecy");
  codes[0x32] = StrToID("bvscav");
  codes[0x33] = StrToID("bvslf");
  codes[0x34] = StrToID("bvtank");
  codes[0x35] = StrToID("bvturr");
  codes[0x36] = StrToID("bvwalk");
  codes[0x37] = StrToID("sbbarr");
  codes[0x38] = StrToID("sbcafe");
  codes[0x39] = StrToID("sbcomm");
  codes[0x3a] = StrToID("sbhang");
  codes[0x3b] = StrToID("sbhqcp");
  codes[0x3c] = StrToID("sblpad");
  codes[0x3d] = StrToID("sblpow");
  codes[0x3e] = StrToID("sbmbld");
  codes[0x3f] = StrToID("sbshld");
  codes[0x40] = StrToID("sbsilo");
  codes[0x41] = StrToID("sbspow");
  codes[0x42] = StrToID("sbtowe");
  codes[0x43] = StrToID("sbwpow");
  codes[0x44] = StrToID("sspilo");
  codes[0x45] = StrToID("sssold");
  codes[0x46] = StrToID("ssuser");
  codes[0x47] = StrToID("svapc");
  codes[0x48] = StrToID("svartl");
  codes[0x49] = StrToID("svcnst");
  codes[0x4a] = StrToID("svfigh");
  codes[0x4b] = StrToID("svhaul");
  codes[0x4c] = StrToID("svhraz");
  codes[0x4d] = StrToID("svltnk");
  codes[0x4e] = StrToID("svmine");
  codes[0x4f] = StrToID("svmuf");
  codes[0x50] = StrToID("svrckt");
  codes[0x51] = StrToID("svrecy");
  codes[0x52] = StrToID("svsav");
  codes[0x53] = StrToID("svscav");
  codes[0x54] = StrToID("svslf");
  codes[0x55] = StrToID("svtank");
  codes[0x56] = StrToID("svturr");
  codes[0x57] = StrToID("svwalk");
  codes[0x58] = StrToID("apammo");
  codes[0x59] = StrToID("apcamr");
  codes[0x5a] = StrToID("apcann");
  codes[0x5b] = StrToID("apmort");
  codes[0x5c] = StrToID("aprepa");
  codes[0x5d] = StrToID("aprock");
  codes[0x5e] = StrToID("apspec");
  codes[0x5f] = StrToID("apwrck");
  codes[0x60] = StrToID("grccmi");
  codes[0x61] = StrToID("nparr");
  codes[0x62] = StrToID("scrap");
  codes[99] = StrToID("apspln");
  codes[100] = StrToID("spspln");
  codes[0x65] = StrToID("gsplint");
  return;
}
