#!/usr/bin/env python3
"""Runs the bz14atk AI task census matrix against the live game.

For each scenario this script:
  1. writes the scenario into addon\\bz14atk\\bz14cfg.odf,
  2. spawns battlezone98redux.exe with bz14_task_census.js injected from
     process start (frida spawn),
  3. lets the engagement run for --run-seconds, capturing [census] JSON
     lines to a per-scenario output file,
  4. kills the process and snapshots logs\\BZLogger.txt next to it.

The census script is the evidence source; this file only orchestrates
scenarios. Raw per-scenario output is preserved so any claim in the reports
can be re-derived from it.

Usage:
  python run_bz14_task_census.py --scenarios avtank:attack avfigh:attack
"""

import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path

import frida

DEFAULT_GAME_ROOT = Path(
    r"C:\Program Files (x86)\GOG Galaxy\Games\Battlezone 98 Redux")

DEFAULT_SCENARIOS = [
    "avtank:attack",
    "avtank:hunt",
    "avfigh:attack",
    "avrckt:attack",
    "avartl:attack",
    "avwalk:attack",
    "avturr:auto",
    "svtank:attack",
    "cvtank:attack",
    "avtank:follow",
    "avtank:defend2",
    "avtank:formation",
    "avtank:auto",
]

# Hostile counterpart per attacker family; same-family duel otherwise.
TARGET_ODFS = {
    "avtank": "svtank",
    "svtank": "avtank",
    "cvtank": "avtank",
    "avfigh": "svfigh",
    "avrckt": "svtank",
    "avartl": "svtank",
    "avwalk": "svtank",
}

CONFIG_TEMPLATE = """\
; Scenario configuration for the bz14atk census run. Generated by
; run_bz14_task_census.py - do not edit by hand.
[Bz14Attack]
count = 1
distance = 80.0
engageDistance = 45.0
targetMove = "none"
command = "{command}"
runSeconds = {run_seconds:.1f}
unitOdf = "{unit}"
targetOdf = "{target}"
[DESCRIPTION]
missionName = "OpenShim BZ1.4 Attack Policy Validation"
[WORKSHOP]
mapType = "instant_action"
customtags = "OpenShim, validation, instant action"
"""


def stop_game():
    subprocess.run(
        ["taskkill", "/F", "/IM", "battlezone98redux.exe"],
        capture_output=True, check=False)
    time.sleep(2)


def write_config(mission_root, unit, command, target, run_seconds):
    cfg = CONFIG_TEMPLATE.format(
        command=command, run_seconds=run_seconds, unit=unit, target=target)
    (mission_root / "bz14cfg.odf").write_text(cfg, encoding="ascii")


def on_message(message, data):
    # console.log from the census script arrives as message type "log".
    if message.get("type") == "send":
        print(message.get("payload", ""))
    elif message.get("type") == "error":
        print("[frida-error] " + str(message.get("description")), file=sys.stderr)


def run_scenario(game_root, repo_root, out_root, scenario, run_seconds):
    tag = scenario.replace(":", "_")
    unit, command = scenario.split(":", 1)
    target = TARGET_ODFS.get(unit, "svtank")
    mission_source = repo_root / "reverse_engineering" / "test_missions" / "bz14atk"
    mission_root = game_root / "addon" / "bz14atk"
    mission_root.mkdir(parents=True, exist_ok=True)
    for item in mission_source.iterdir():
        if item.is_file():
            shutil.copy2(item, mission_root / item.name)

    census_script = repo_root / "reverse_engineering" / "bz14_task_census.js"
    out_file = out_root / f"{tag}.txt"

    write_config(mission_root, unit, command, target,
                 max(run_seconds - 20, 25))
    stop_game()

    logger = game_root / "logs" / "BZLogger.txt"
    logger_start = logger.stat().st_mtime if logger.exists() else 0

    print(f"[run] {scenario} (unit={unit} cmd={command} target={target})")

    # Launch the game NORMALLY. Frida spawn mode perturbs this build's
    # packer (module .rdata reads as zeros and module-VA hooks never fire),
    # so the census attaches only after the mission is verifiably running -
    # exactly the methodology that produced the proven prior tallies.
    # Rapid relaunches occasionally die during GOG/shader init; retry once.
    session = None
    for attempt in range(2):
        proc = subprocess.Popen(
            [str(game_root / "battlezone98redux.exe"), "bz14atk.bzn"],
            cwd=str(game_root))
        out_fh = None
        try:
            attach_deadline = time.time() + 120
            started = False
            while time.time() < attach_deadline:
                time.sleep(2)
                if proc.poll() is not None:
                    break
                if logger.exists() and logger.stat().st_mtime > logger_start:
                    tail = read_tail(logger, 64 * 1024)
                    if "[BZ14ATK] tel t=" in tail:
                        started = True
                        break
            if not started:
                raise RuntimeError(
                    f"mission telemetry never appeared "
                    f"(attempt {attempt + 1}, exit={proc.poll()})")

            out_fh = open(out_file, "a", encoding="utf-8")
            session = frida.attach(proc.pid)
            script = session.create_script(
                census_script.read_text(encoding="utf-8"))

            def handle(*a):
                # set_log_handler passes (level, text); 'message' passes
                # (message, data).
                if len(a) == 2 and isinstance(a[0], str):
                    line = str(a[1])
                else:
                    line = _format_message(a[0]).rstrip("\n")
                out_fh.write(line + "\n")
                out_fh.flush()
                if "[census]" in line:
                    print("  " + line[:150])

            # console.log arrives through the log channel, not 'message'.
            script.set_log_handler(handle)
            script.on("message", handle)
            script.load()

            deadline = time.time() + run_seconds
            while time.time() < deadline and proc.poll() is None:
                time.sleep(5)
            break
        except Exception:
            if attempt == 1:
                raise
            stop_game()
            time.sleep(6)
        finally:
            if session is not None:
                try:
                    session.detach()
                except Exception:
                    pass
            if proc.poll() is None:
                stop_game()

    logger_copy = out_root / f"{tag}.BZLogger.txt"
    if logger.exists():
        shutil.copy2(logger, logger_copy)

    census_lines = count_pattern(out_file, "[census]")
    telemetry_lines = count_pattern(logger_copy, "[BZ14ATK] tel t=")
    print(f"[done] {scenario}: census-lines={census_lines} "
          f"telemetry-lines={telemetry_lines}")
    return census_lines > 0


def _format_message(message):
    if message.get("type") == "log":
        return str(message.get("payload", "")) + "\n"
    if message.get("type") == "error":
        return "[frida-error] " + str(message.get("description")) + "\n"
    return ""


def read_tail(path, nbytes):
    size = path.stat().st_size
    with open(path, "rb") as fh:
        if size > nbytes:
            fh.seek(size - nbytes)
        return fh.read().decode("utf-8", errors="ignore")


def count_pattern(path, needle):
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text(encoding="utf-8",
                                            errors="ignore").splitlines()
               if needle in line)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", default=str(DEFAULT_GAME_ROOT))
    parser.add_argument("--out-root", default="")
    parser.add_argument("--run-seconds", type=int, default=60)
    parser.add_argument("--scenarios", nargs="+", default=DEFAULT_SCENARIOS)
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    game_root = Path(args.game_root)
    out_root = (Path(args.out_root) if args.out_root else
                repo_root / "reverse_engineering" / "snapshots" /
                "bz14_census" / time.strftime("%Y%m%d_%H%M%S"))
    out_root.mkdir(parents=True, exist_ok=True)

    failures = []
    stop_game()
    for scenario in args.scenarios:
        try:
            if not run_scenario(game_root, repo_root, out_root, scenario,
                                args.run_seconds):
                failures.append(scenario)
        except Exception as exc:
            print(f"[error] {scenario}: {exc}", file=sys.stderr)
            failures.append(scenario)
            stop_game()
    stop_game()

    print(f"[complete] outputs under {out_root}")
    if failures:
        print("[failed scenarios] " + ", ".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
